title: "Benyam Seifu"
email: binychanyalew@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I am Benyam a mobile and full-stack web developer.
  I put myself to the world in such a way that the rest of the world says "Wow that's cool!"
baseurl: "/"
url: "https://benyam7.github.io/portfolio-template/"
twitter_username: benyam_7
github_username: benyam7

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
