# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update
        run: sudo apt-get update
      - name: Install
        run: sudo apt-get install xvfb wkhtmltopdf
      - name: Convert
        run: |
          mkdir cv
          portfolioURL=$(grep 'url:' _config.yml | tail -n1 | awk '{ print s $2}' | tr -d \")
          echo xvfb-run wkhtmltopdf ${portfolioURL} cv/resume.pdf > resume.pdf
          cd ..

      - name: Archive convert results
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: cv

  download_cv:
    name: download cv
    runs-on; ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: resume
      - run: cat resume.pdf

    # - uses: actions/checkout@master
    #   with:
    #     fetch-depth: 1
    # - name: write to repo
    #   run: |
    #     printf '%b\n' "<p>hello </p>" > test.html
    # - name: Push changes to repo
    #   run: |
    #     REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    #     git config user.email "${{ github.actor }}@users.noreply.github.com"
    #     git config user.name "${{ github.actor }}"

    #     git pull ${REMOTE}
    #     git checkout master
    #     git add .
    #     git status
    #     git commit -am "add cv"
    #     git push ${REMOTE} master
