name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_1:
    name: generate pdf and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update
        run: sudo apt-get update
      - name: Install
        run: sudo apt-get install xvfb wkhtmltopdf
      - name: Convert
        run: |
          mkdir cv
          portfolioURL=$(grep 'url:' _config.yml | tail -n1 | awk '{ print s $2}' | tr -d \")
          xvfb-run wkhtmltopdf ${portfolioURL} cv/resume.pdf
          pwd
          ls cv
          # cd ..
          ls
      - name: Archive convert results
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: /home/runner/work/portfolio-template/portfolio-template/cv

  job_2:
    name: download and write to repo
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download result for job 1
        uses: actions/download-artifact@v2
        with:
          name: resume
      - shell: bash
        run: |
          pwd
          ls /d/a/portfolio-template/portfolio-template
          echo "all "
          ls

          # mkdir test

          mv -f /d/a/portfolio-template/portfolio-template/resume.pdf ${{github.workspace}}
  job_3:
    name: push changes
    needs: job_2
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Push changes to repo
        run: |
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git pull ${REMOTE}
          git checkout master
          git add .
          git status
          git commit -am "Add new comment"
          git push ${REMOTE} master
