# This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run.
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Update
#         run: sudo apt-get update
#       - name: Install
#         run: sudo apt-get install xvfb wkhtmltopdf
#       - name: Convert
#         run: |
#           mkdir cv
#           portfolioURL=$(grep 'url:' _config.yml | tail -n1 | awk '{ print s $2}' | tr -d \")
#           xvfb-run wkhtmltopdf ${portfolioURL} cv/resume.pdf > resume.pdf
#           cd ..
#       - name: Archive convert results
#         uses: actions/upload-artifact@v2
#         with:
#           name: resume
#           path: cv

#       # - name: write
#       #   uses: DamianReeves/write-file-action
#       #   with:
#       #     path: "cv/.pdf"
#       #     contents: |
#       #       echo resume.pdf
#       #     write-mode: overwrite

#       - uses: actions/checkout@master
#         with:
#           fetch-depth: 1
#       - name: write to repo
#         uses: actions/download-artifact@v2
#         with:
#           name: resume
#         run: |
#           cat resume.pdf
#           # printf '%b\n' resume.pdf  > cv/cv.pdf
# - name: Push changes to repo
#   run: |
#     REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#     git config user.email "${{ github.actor }}@users.noreply.github.com"
#     git config user.name "${{ github.actor }}"
#     git pull ${REMOTE}
#     git checkout master
#     git add .
#     git status
#     git commit -am "Add new comment"
#     git push ${REMOTE} master

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_1:
    name: generate pdf and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update
        run: sudo apt-get update
      - name: Install
        run: sudo apt-get install xvfb wkhtmltopdf
      - name: Convert
        run: |
          # mkdir cv
          portfolioURL=$(grep 'url:' _config.yml | tail -n1 | awk '{ print s $2}' | tr -d \")
          xvfb-run wkhtmltopdf ${portfolioURL} cv/resume.pdf > resume.pdf
          # cd ..
      - name: Archive convert results
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf

      # - shell: bash
      #   run: |
      #     expr 3 + 7 > math-homework.txt
      # - name: Upload math result for job 1
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: homework
      #     path: math-homework.txt

  job_2:
    name: download and write to repo
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download result for job 1
        uses: actions/download-artifact@v2
        with:
          name: resume
        - shell: bash
      - uses: actions/checkout@master
          with:
            fetch-depth: 1
      - name: turn in to file
        run: |
          printf '%b\n' resume.pdf  > resume.pdf
          # cat resume.pdf
          # value=`cat math-homework.txt`
          # expr $value \* 9 > math-homework.txt

      - name: Push changes to repo
        run: |
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git pull ${REMOTE}
          git checkout master
          git add .
          git status
          git commit -am "Add new comment"
          git push ${REMOTE} master
